import { Link, NavLink as RouterNavLink, useNavigate } from "react-router-dom";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { ArrowRight, ChevronDown, Menu, Minus, Plus, Search, ShoppingCart, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { products, categories } from "@/lib/catalog";
import logo from "@/assets/Pras_Logo.png";

const CommerceContext = createContext(null);

export function CommerceProvider({ children }) {
  const [cart, setCart] = useState({});
  const [wishlist, setWishlist] = useState([]);
  const [compare, setCompare] = useState([]);
  const [cartOpen, setCartOpen] = useState(false);
  const value = useMemo(() => ({ cart, wishlist, compare, cartOpen, setCartOpen, addToCart: (id, quantity = 1) => { setCart((old) => ({ ...old, [id]: (old[id] ?? 0) + quantity })); setCartOpen(true); }, updateCart: (id, quantity) => setCart((old) => { const next = { ...old }; if (quantity <= 0) delete next[id]; else next[id] = quantity; return next; }), toggleWishlist: (id) => setWishlist((old) => old.includes(id) ? old.filter((item) => item !== id) : [...old, id]), toggleCompare: (id) => setCompare((old) => old.includes(id) ? old.filter((item) => item !== id) : old.length < 3 ? [...old, id] : old) }), [cart, wishlist, compare, cartOpen]);
  return <CommerceContext.Provider value={value}>{children}<CartDrawer /></CommerceContext.Provider>;
}

export function useCommerce() { const value = useContext(CommerceContext); if (!value) throw new Error("CommerceProvider missing"); return value; }

export function SiteHeader() {
  const [mobileOpen, setMobileOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [mega, setMega] = useState(false); const [query, setQuery] = useState("");
  const navigate = useNavigate();
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); onScroll(); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  const submit = (e) => { e.preventDefault(); navigate(query ? `/products?q=${encodeURIComponent(query)}` : "/products"); setMobileOpen(false); };
  const links = [{ label: "Home", to: "/" }, { label: "About Us", to: "/about" }, { label: "Our Team", to: "/team" }, { label: "Contact", to: "/contact" }];
  return <header className={`sticky top-0 z-50 border-b border-line bg-ground/95 backdrop-blur-md transition-all ${scrolled ? "shadow-soft" : ""}`}>
    <div className={`container-page grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 transition-all ${scrolled ? "h-16" : "h-20"}`}>
      <div className="flex min-w-0 items-center gap-8"><Link to="/" className="flex min-w-0 items-center gap-3"><img src={logo} alt="Pras Minerals" width={48} height={48} className="size-12 shrink-0 rounded-full object-cover" /><span className="min-w-0"><strong className="block truncate font-display text-lg">Pras Minerals</strong><small className="hidden text-[10px] font-semibold uppercase tracking-widest text-muted-foreground sm:block">Mineral Exports</small></span></Link>
        <nav className="hidden items-center gap-5 xl:flex">{links.slice(0,1).map((l) => <NavLink key={l.to} {...l} />)}<div onMouseEnter={() => setMega(true)} onMouseLeave={() => setMega(false)} className="relative"><Link to="/products" className="inline-flex items-center gap-1 text-sm font-medium text-muted-foreground hover:text-foreground">Products <ChevronDown className="size-3" /></Link>{mega && <MegaMenu />}</div>{links.slice(1).map((l) => <NavLink key={l.to} {...l} />)}</nav></div>
      <div className="flex shrink-0 items-center gap-1.5"><form onSubmit={submit} className="hidden items-center rounded-xl border border-line bg-card px-3 lg:flex"><Search className="size-4 text-muted-foreground" /><input aria-label="Search products" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products" className="h-10 w-32 bg-transparent px-2 text-sm outline-none" /></form><Button variant="ghost" size="icon" className="xl:hidden" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Menu">{mobileOpen ? <X /> : <Menu />}</Button></div>
    </div>{mobileOpen && <div className="border-t border-line bg-card px-5 py-5 xl:hidden"><form onSubmit={submit} className="mb-4 flex rounded-xl border border-line bg-ground"><input aria-label="Mobile search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products" className="h-11 min-w-0 flex-1 bg-transparent px-3 outline-none" /><Button size="icon" aria-label="Submit search"><Search /></Button></form><nav className="grid gap-1"><NavLink label="Home" to="/" /><NavLink label="Products" to="/products" />{links.slice(1).map((l) => <NavLink key={l.to} {...l} />)}</nav></div>}</header>;
}

function NavLink({ label, to }) { return <RouterNavLink to={to} end={to === "/"} className={({ isActive }) => `block rounded-lg px-2 py-2 text-sm font-medium transition-colors hover:text-foreground ${isActive ? "text-foreground" : "text-muted-foreground"}`}>{label}</RouterNavLink>; }
function MegaMenu() { return <div className="absolute left-1/2 top-full w-[680px] -translate-x-1/2 pt-4"><div className="grid grid-cols-2 gap-6 rounded-2xl border border-line bg-card p-6 shadow-elevated"><div><p className="eyebrow">Product families</p><div className="mt-3 grid grid-cols-2 gap-2">{categories.map((c) => <Link key={c.name} to={`/products?q=${encodeURIComponent(c.name)}`} className="rounded-xl p-3 hover:bg-brand-soft"><strong className="block text-sm">{c.name}</strong><small className="text-muted-foreground">{c.count || "Custom"} solutions</small></Link>)}</div></div><div className="rounded-xl bg-ink p-6 text-ink-foreground"><p className="eyebrow text-ink-foreground/60">Engineering support</p><h3 className="mt-3 font-display text-xl font-semibold">Built to your specification.</h3><p className="mt-2 text-sm text-ink-foreground/70">Share a drawing for feasibility, lead time, and pricing.</p><Button asChild variant="accent" className="mt-5"><Link to="/contact">Request a quote <ArrowRight /></Link></Button></div></div></div>; }

export function ProductCard({ product, list = false }) { return <article className={`group overflow-hidden rounded-2xl border border-line bg-card shadow-card transition hover:-translate-y-1 hover:border-brand/35 hover:shadow-elevated ${list ? "grid sm:grid-cols-[240px_1fr]" : ""}`}><Link to={`/products/${product.id}`} className="relative block overflow-hidden bg-ground"><img src={product.image} alt={product.name} width={800} height={600} loading="lazy" className={`w-full object-cover transition duration-500 group-hover:scale-105 ${list ? "h-full min-h-56" : "aspect-[4/3]"}`} /><span className="absolute left-3 top-3 rounded-full bg-card/95 px-2.5 py-1 text-[10px] font-bold uppercase text-brand">{product.category}</span></Link><div className="flex flex-col justify-center p-5"><p className="text-xs font-semibold text-muted-foreground">{product.model}</p><Link to={`/products/${product.id}`}><h3 className="mt-1 font-display text-lg font-semibold leading-snug">{product.name}</h3></Link><Button asChild className="mt-4 w-fit"><Link to="/contact">Enquire now <ArrowRight className="size-4" /></Link></Button></div></article>; }

function CartDrawer() { const { cart, cartOpen, setCartOpen, updateCart } = useCommerce(); const items = Object.entries(cart).map(([id, quantity]) => ({ product: products.find((p) => p.id === id), quantity })).filter((x) => Boolean(x.product)); const total = items.reduce((sum, x) => sum + (x.product.price ?? 0) * x.quantity, 0); return <><button aria-label="Close cart overlay" onClick={() => setCartOpen(false)} className={`fixed inset-0 z-[60] bg-overlay transition ${cartOpen ? "visible opacity-100" : "invisible opacity-0"}`} /><aside aria-label="Shopping cart" className={`fixed right-0 top-0 z-[70] flex h-full w-full max-w-md flex-col bg-card shadow-elevated transition-transform duration-300 ${cartOpen ? "translate-x-0" : "translate-x-full"}`}><div className="flex items-center justify-between border-b border-line p-5"><div><h2 className="font-display text-xl font-semibold">Your cart</h2><p className="text-xs text-muted-foreground">{items.length} product lines</p></div><Button variant="ghost" size="icon" onClick={() => setCartOpen(false)} aria-label="Close cart"><X /></Button></div><div className="flex-1 overflow-y-auto p-5">{items.length === 0 ? <div className="grid h-full place-items-center text-center"><div><ShoppingCart className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-medium">Your cart is empty</p></div></div> : <div className="space-y-4">{items.map(({ product, quantity }) => <div key={product.id} className="grid grid-cols-[72px_1fr] gap-3 border-b border-line pb-4"><img src={product.image} alt="" className="size-[72px] rounded-lg object-cover" /><div><div className="flex justify-between gap-2"><div><strong className="text-sm">{product.name}</strong><p className="text-xs text-muted-foreground">{product.model}</p></div><Button variant="ghost" size="icon" onClick={() => updateCart(product.id, 0)} aria-label="Remove"><Trash2 /></Button></div><div className="mt-2 flex items-center justify-between"><div className="flex items-center rounded-lg border border-line"><Button variant="ghost" size="icon" onClick={() => updateCart(product.id, quantity - 1)} aria-label="Decrease"><Minus /></Button><span className="w-7 text-center text-sm">{quantity}</span><Button variant="ghost" size="icon" onClick={() => updateCart(product.id, quantity + 1)} aria-label="Increase"><Plus /></Button></div><strong>${((product.price ?? 0) * quantity).toFixed(2)}</strong></div></div></div>)}</div>}</div><div className="border-t border-line p-5"><div className="flex justify-between font-display text-lg font-semibold"><span>Subtotal</span><span>${total.toFixed(2)}</span></div><p className="mt-1 text-xs text-muted-foreground">Shipping and tax calculated at checkout.</p><Button className="mt-4 w-full" size="lg">Proceed to checkout <ArrowRight /></Button><Button variant="outline" className="mt-2 w-full" onClick={() => setCartOpen(false)}>Continue shopping</Button></div></aside></>; }

export function SiteFooter() { return <footer className="mt-20 bg-ink text-ink-foreground"><div className="container-page grid gap-12 py-16 lg:grid-cols-[1.4fr_3fr]"><div><div className="flex items-center gap-3"><img src={logo} alt="Pras Minerals" width={48} height={48} className="size-12 rounded-full object-cover" /><strong className="font-display text-lg">Pras Minerals</strong></div><p className="mt-4 max-w-sm text-sm leading-relaxed text-ink-foreground/65">Manufacturer, supplier, and exporter of quality minerals for industries worldwide.</p><div className="mt-6 space-y-1 text-sm text-ink-foreground/65"><p>prasmineralsexports@example.com</p><p>Kondapur, Hyderabad, Telangana, India</p></div></div><div className="grid grid-cols-2 gap-8">{[["Products","Product Categories","Featured Products","Custom Products"],["Company","About Us","Contact"]].map(([title,...items]) => <div key={title}><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-4 space-y-2 text-sm text-ink-foreground/60">{items.map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div></div><div className="border-t border-ink-foreground/10"><div className="container-page flex flex-col justify-between gap-3 py-6 text-xs text-ink-foreground/50 sm:flex-row"><span>© 2026 Pras Minerals. All rights reserved.</span><span>Privacy Policy · Terms & Conditions · Cookie Policy</span></div></div></footer>; }
