import { Link } from "react-router-dom";
import { ArrowRight, Award, Box, Download, FileText, Globe2, Headphones, Lightbulb, ShieldCheck, SlidersHorizontal, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import manufacturingImage from "@/assets/minerals/soapstone.jpg";
import aboutTeaserImage from "@/assets/mining/quarry-blasting.jpg";
import { categories, industries, products } from "@/lib/catalog";

const categoryImages = Object.fromEntries(products.map((p) => [p.category, p.image]));

export function PageIntro({ eyebrow, title, description }) { return <section className="border-b border-line bg-card"><div className="container-page py-16 sm:py-24"><p className="eyebrow text-brand">{eyebrow}</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold leading-tight sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted-foreground">{description}</p></div></section>; }

export function AboutTeaser() { return <section className="border-y border-line bg-card"><div className="container-page section-pad"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><img src={aboutTeaserImage} alt="Controlled rock blasting at a quarry site" width={1200} height={900} loading="lazy" className="aspect-[4/3] w-full rounded-2xl object-cover shadow-card lg:order-2" /><div><p className="eyebrow text-brand">About Us</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-4xl">A decade of trusted mineral exports.</h2><p className="mt-4 leading-relaxed text-muted-foreground">Pras Mineral Exports Pvt. Ltd. is a Hyderabad-based processor, supplier, and exporter of Potash Feldspar, Soda Feldspar, Quartz, and Soapstone, established in 2010. Our proximity to mines and the seaports of Krishnapatnam and Chennai gives us a strategic edge — easy access to raw material and lower operational costs we pass on to clients worldwide.</p><Button asChild className="mt-6"><Link to="/about">Learn more about us <ArrowRight /></Link></Button></div></div></div></section>; }

export function CategoryGrid() { return <section className="container-page section-pad"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow text-brand">Catalog</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Explore our products</h2></div><Button asChild variant="ghost"><Link to="/products">View all <ArrowRight /></Link></Button></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category, index) => <Link key={category.name} to={`/products?q=${encodeURIComponent(category.name)}`} className="group flex flex-col overflow-hidden rounded-xl border border-line bg-card shadow-card transition hover:-translate-y-1 hover:border-brand/35 hover:shadow-elevated"><div className="relative aspect-[16/11] w-full overflow-hidden bg-ground"><img src={categoryImages[category.name]} alt="" width={360} height={248} loading="lazy" className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105" /><span className="absolute left-2.5 top-2.5 rounded-full bg-card/95 px-2 py-0.5 text-[10px] font-bold text-brand">0{index + 1}</span></div><div className="flex flex-1 flex-col p-4"><h3 className="font-display text-base font-semibold">{category.name}</h3><span className="mt-2 inline-flex items-center gap-1.5 text-xs font-semibold text-brand">View products <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-1" /></span></div></Link>)}</div></section>; }

export function IndustriesSection() { return <section className="container-page section-pad"><div><p className="eyebrow text-brand">Applications</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Minerals that travel across industries.</h2><p className="mt-4 max-w-xl text-muted-foreground">From bulk export orders to specialized grades, our minerals are supplied for demanding industrial applications worldwide.</p><div className="mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-line bg-line sm:grid-cols-3 lg:grid-cols-5">{industries.map((industry) => <div key={industry} className="bg-card p-4 text-sm font-semibold">{industry}</div>)}</div></div></section>; }

export function WhyUs() { const items = [[ShieldCheck,"Quality assurance"],[Lightbulb,"Advanced technology"],[Wrench,"Custom engineering"],[Box,"Reliable supply"],[Globe2,"Global support"],[Award,"Certified quality"]]; return <section className="bg-brand-soft"><div className="container-page section-pad"><div className="text-center"><p className="eyebrow text-brand">Why Pras Minerals</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Confidence at every stage</h2></div><div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-3">{items.map(([Icon,title]) => <div key={title} className="bg-card p-7"><Icon className="size-6 text-brand" /><h3 className="mt-5 font-display text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Documented processes, responsive expertise, and traceable execution from inquiry through delivery.</p></div>)}</div></div></section>; }

export function AboutBand() { return <section className="container-page section-pad"><div className="grid overflow-hidden rounded-3xl bg-ink text-ink-foreground lg:grid-cols-2"><img src={manufacturingImage} alt="Soapstone lump ready for export" width={1600} height={1100} loading="lazy" className="h-full min-h-96 w-full object-cover" /><div className="p-8 sm:p-12"><p className="eyebrow text-ink-foreground/50">Built for the long term</p><h2 className="mt-4 font-display text-3xl font-semibold sm:text-4xl">Mining discipline. Global reach.</h2><p className="mt-4 leading-relaxed text-ink-foreground/65">Pras Minerals supports customers worldwide with reliable extraction, quality grading, and practical export support from Hyderabad, India.</p><div className="mt-9 grid grid-cols-2 gap-7">{[["15+","Years experience"],["GST","Verified supplier"],["7","Mineral categories"],["Global","Export inquiries"]].map(([value,label]) => <div key={label}><strong className="font-display text-2xl">{value}</strong><p className="mt-1 text-xs text-ink-foreground/55">{label}</p></div>)}</div><Button asChild variant="accent" className="mt-9"><Link to="/about">Learn more <ArrowRight /></Link></Button></div></div></section>; }

export function ResourcesGrid() { const data = [[FileText,"Datasheets"],[Download,"Product catalog"],[SlidersHorizontal,"Technical documentation"],[Lightbulb,"Application notes"],[Headphones,"FAQ & support"],[Download,"Downloads"]]; return <section className="border-y border-line bg-card"><div className="container-page section-pad"><p className="eyebrow text-brand">Technical resources</p><h2 className="mt-3 font-display text-3xl font-semibold sm:text-4xl">Information for better decisions</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.map(([Icon,title]) => <Link key={title} to="/resources" className="group flex items-center gap-4 rounded-xl border border-line p-5 transition hover:border-brand/35 hover:bg-brand-soft"><span className="grid size-11 shrink-0 place-items-center rounded-lg bg-brand-soft text-brand"><Icon className="size-5" /></span><div><strong className="font-display">{title}</strong><p className="mt-1 text-xs text-muted-foreground">View and download <ArrowRight className="ml-1 inline size-3 transition group-hover:translate-x-1" /></p></div></Link>)}</div></div></section>; }

export function QuoteForm() { return <form onSubmit={(e) => e.preventDefault()} className="grid gap-4 rounded-2xl border border-line bg-card p-6 shadow-card sm:grid-cols-2"><label className="text-sm font-medium">Name<input required className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 outline-none focus:ring-2 focus:ring-ring" /></label><label className="text-sm font-medium">Company<input required className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 outline-none focus:ring-2 focus:ring-ring" /></label><label className="text-sm font-medium">Email<input type="email" required className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 outline-none focus:ring-2 focus:ring-ring" /></label><label className="text-sm font-medium">Phone<input type="tel" className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 outline-none focus:ring-2 focus:ring-ring" /></label><label className="text-sm font-medium">Product<input className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 outline-none focus:ring-2 focus:ring-ring" /></label><label className="text-sm font-medium">Quantity<input type="number" min="1" className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 outline-none focus:ring-2 focus:ring-ring" /></label><label className="text-sm font-medium sm:col-span-2">Requirements<textarea rows={5} className="mt-2 w-full rounded-lg border border-input bg-background p-3 outline-none focus:ring-2 focus:ring-ring" /></label><Button size="lg" className="sm:col-span-2">Submit request <ArrowRight /></Button></form>; }
